// <auto-generated />
namespace TuPrecio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201604131704467_Initial-Seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
